// TestResources.swift
// Generated by SwiftResources — do not edit

import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif
#if canImport(SwiftUI)
import SwiftUI
#endif

private class BundleFinder {}

enum TestResources {
    private static let bundle = Bundle(for: BundleFinder.self)

    // MARK: - Font Resource

    struct FontResource: Sendable, Hashable {
        let fontName: String
        let bundle: Bundle

        #if canImport(UIKit)
        func uiFont(size: CGFloat) -> UIFont? {
            UIFont(name: fontName, size: size)
        }
        #endif

        #if canImport(AppKit) && !targetEnvironment(macCatalyst)
        func nsFont(size: CGFloat) -> NSFont? {
            NSFont(name: fontName, size: size)
        }
        #endif

        #if canImport(SwiftUI)
        func font(size: CGFloat) -> Font {
            Font.custom(fontName, size: size)
        }
        #endif
    }

    // MARK: - Image Resource

    struct ImageResource: Sendable, Hashable {
        let name: String
        let bundle: Bundle

        #if canImport(UIKit)
        var uiImage: UIImage? {
            UIImage(named: name, in: bundle, with: nil)
        }
        #endif

        #if canImport(AppKit) && !targetEnvironment(macCatalyst)
        var nsImage: NSImage? {
            bundle.image(forResource: name)
        }
        #endif

        #if canImport(SwiftUI)
        var image: Image {
            Image(name, bundle: bundle)
        }
        #endif
    }

    // MARK: - File Resource

    struct FileResource: Sendable, Hashable {
        let name: String
        let fileExtension: String
        let bundle: Bundle

        var url: URL? {
            bundle.url(forResource: name, withExtension: fileExtension)
        }

        var data: Data? {
            guard let url = url else { return nil }
            return try? Data(contentsOf: url)
        }
    }

    // MARK: - Fonts

    enum fonts {
        private static let _register: Void = { registerFonts() }()

        static var lilexRegular: FontResource { _ = _register; return FontResource(fontName: "Lilex-Regular", bundle: bundle) }
    }

    // MARK: - Images

    enum images {
        static let logo = ImageResource(name: "logo", bundle: bundle)
    }

    // MARK: - Files

    enum files {
        static let config = FileResource(name: "config", fileExtension: "json", bundle: bundle)
    }

    // MARK: - Font Registration

    static func registerFonts() {
        #if canImport(CoreText)
        let fontFiles: [(name: String, ext: String)] = [
            ("Lilex-Regular", "ttf"),
        ]
        for font in fontFiles {
            guard let url = bundle.url(forResource: font.name, withExtension: font.ext) else { continue }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
        #endif
    }
}
