// TestResources.swift
// Generated by SwiftResources — do not edit

import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif
#if canImport(SwiftUI)
import SwiftUI
#endif

private final class BundleFinder {
    static let resourceBundle: Bundle = {
        // When built with SPM, Bundle.module is available and preferred
        #if SWIFT_PACKAGE
        return Bundle.module
        #else
        let bundleName = "TestResources_TestResources"
        let bundleResourceURL = Bundle(for: BundleFinder.self).resourceURL

        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,
            // Bundle should be present here when the package is linked into a framework.
            bundleResourceURL,
            // For command-line tools.
            Bundle.main.bundleURL,
            // Bundle should be present here when running previews from a different package.
            bundleResourceURL?.deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent(),
            bundleResourceURL?.deletingLastPathComponent().deletingLastPathComponent(),
            // Other package or embedding scenarios.
            bundleResourceURL?.deletingLastPathComponent(),
        ]

        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }

        // Fallback to the bundle containing this code (works for Bazel builds)
        return Bundle(for: BundleFinder.self)
        #endif
    }()
}

enum TestResources {
    private static let bundle = BundleFinder.resourceBundle

    // MARK: - Font Resource

    struct FontResource: Sendable, Hashable {
        let fontName: String
        let bundle: Bundle

        #if canImport(UIKit)
        func uiFont(size: CGFloat, relativeTo textStyle: UIFont.TextStyle? = nil) -> UIFont? {
            guard let font = UIFont(name: fontName, size: size) else { return nil }
            guard let textStyle else { return font }
            return UIFontMetrics(forTextStyle: textStyle).scaledFont(for: font)
        }
        #endif

        #if canImport(AppKit) && !targetEnvironment(macCatalyst)
        func nsFont(size: CGFloat) -> NSFont? {
            NSFont(name: fontName, size: size)
        }
        #endif

        #if canImport(SwiftUI)
        func font(size: CGFloat, relativeTo textStyle: Font.TextStyle? = nil) -> Font {
            if let textStyle {
                return Font.custom(fontName, size: size, relativeTo: textStyle)
            }
            return Font.custom(fontName, size: size)
        }
        #endif
    }

    // MARK: - Image Resource

    struct ImageResource: Sendable, Hashable {
        let name: String
        let bundle: Bundle

        #if canImport(UIKit)
        var uiImage: UIImage? {
            UIImage(named: name, in: bundle, with: nil)
        }
        #endif

        #if canImport(AppKit) && !targetEnvironment(macCatalyst)
        var nsImage: NSImage? {
            bundle.image(forResource: name)
        }
        #endif

        #if canImport(SwiftUI)
        var image: Image {
            Image(name, bundle: bundle)
        }
        #endif
    }

    // MARK: - File Resource

    struct FileResource: Sendable, Hashable {
        let name: String
        let fileExtension: String
        let bundle: Bundle

        var url: URL? {
            bundle.url(forResource: name, withExtension: fileExtension)
        }

        var data: Data? {
            guard let url = url else { return nil }
            return try? Data(contentsOf: url)
        }
    }

    // MARK: - Fonts

    enum fonts {
        private static let _register: Void = { registerFonts() }()

        static var lilexRegular: FontResource { _ = _register; return FontResource(fontName: "Lilex-Regular", bundle: bundle) }
    }

    // MARK: - Images

    enum images {
        static let logo = ImageResource(name: "logo", bundle: bundle)
    }

    // MARK: - Files

    enum files {
        static let config = FileResource(name: "config", fileExtension: "json", bundle: bundle)
    }

    // MARK: - Font Registration

    static func registerFonts() {
        #if canImport(CoreText)
        let fontFiles: [(name: String, ext: String)] = [
            ("Lilex-Regular", "ttf"),
        ]
        for font in fontFiles {
            guard let url = bundle.url(forResource: font.name, withExtension: font.ext) else { continue }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
        #endif
    }
}
