name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The new version to tag, ex: 1.0.0'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        run: |
          set -euo pipefail

          COPYFILE_DISABLE=1 tar czvf "rules_swift_resources.$TAG.tar.gz" ./*
          gh release create "$TAG" --title "$TAG" --target "$GITHUB_REF_NAME" --generate-notes "rules_swift_resources.$TAG.tar.gz"
        env:
          TAG: ${{ inputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-bcr:
    needs: create-release
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.2.0
    with:
      tag_name: ${{ inputs.tag }}
      registry_fork: jeffhodsdon/bazel-central-registry
      attest: false
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
